export PATH=$HOME/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin

export ZSH=$HOME/.config/zsh
ZSH_CACHE_DIR="$HOME/.cache/zsh"

export VISUAL=vim
export EDITOR=$VISUAL
export PAGER=less
export LESS=-R

setopt long_list_jobs
setopt interactivecomments
setopt multios
setopt prompt_subst

# Load color associative array
autoload -Uz colors && colors

source $ZSH/plugins/zsh-git-prompt/zshrc.sh

DOTHOME=$HOME/.dotfiles/files
for file ($DOTHOME/*/*.main.zsh); do
	source $file
done

source $DOTHOME/zsh/theme-cpollet.zsh
source $DOTHOME/zsh/completion.zsh
source $DOTHOME/zsh/history.zsh

alias dot_update='git -C ~/.dotfiles pull'

[ -f $HOME/.zsh_aliases ] && source ~/.zsh_aliases

# must be the last one (https://github.com/zsh-users/zsh-syntax-highlighting/blob/master/INSTALL.md)
source $ZSH/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh