#!/bin/bash

export VISUAL=vim
export EDITOR="$VISUAL"

alias ll='ls -l'
alias la='ls -la'
alias ..="cd .."
alias -- -="cd -"

alias f='find . -name'
alias fjava='find . -name "*.java"'
alias fperl='find . -name "*.pl"'
alias ftmpl='find . -name "*.tmpl"'
alias fproperties='find . -name "*.properties"'

alias citrix='/opt/Citrix/ICAClient/selfservice'

alias vi_alias='$EDITOR ~/.zsh_aliases && . ~/.zsh_aliases'
alias vi_env='$EDITOR ~/.bash_env && . ~/.bash_env'

alias svi='sudo $EDITOR'

alias hosts='svi /etc/hosts'

# alias s='sublime_text'
alias reads='read -s'

alias rot13="tr 'A-Za-z' 'N-ZA-Mn-za-m'"
