---
- name: Create ~/.gitconfig symlink
  file:
    src: ~/.dotfiles/files/git/gitconfig
    dest: ~/.gitconfig
    state: link

- name: Create ~/.gitignore symlink
  file:
    src: ~/.dotfiles/files/git/gitignore
    dest: ~/.gitignore
    state: link