---
- name: Create ~/.config
  file:
    path: ~/.config
    state: directory

- name: Fetch execute_dotfile_playbook.yml
  fetch:
    src: ~/.dotfiles/ansible/tasks/execute_dotfile_playbook.yml
    dest: "{{ tmp_dir }}"
  changed_when: false

- name: Execute common tasks
  include_tasks: "{{ tmp_dir }}/localhost/home/{{ current_user }}/.dotfiles/ansible/tasks/execute_dotfile_playbook.yml"
  vars:
    playbooks:
      - zsh
      - ls
      - git
      - vim
      - tmux
  with_items: "{{ playbooks }}"
  loop_control:
    loop_var: playbook

- name: Fetch gnome tasks
  tags: gnome
  fetch:
    src: ~/.dotfiles/ansible/tasks/gnome.yml
    dest: "{{ tmp_dir }}"
  changed_when: false

- name: Execute gnome tasks
  include_tasks: "{{ tmp_dir }}/localhost/home/{{ current_user }}/.dotfiles/ansible/tasks/gnome.yml"
  tags: gnome