#!/bin/bash

alias addr='getent hosts'
alias lsop='sudo netstat -tap'

alias serve='echo http://localhost:8000 && python -m SimpleHTTPServer'

alias hosts='sudo $EDITOR /etc/hosts'
alias dnsflush='sudo service dnsmasq restart'
